// ============================================================
// GYM DATA - Ejercicios, deportes y cardio completos
// ============================================================

export const MUSCLE_GROUPS = [
  { id: 'chest', label: 'Pecho' },
  { id: 'back', label: 'Espalda' },
  { id: 'triceps', label: 'Tríceps' },
  { id: 'biceps', label: 'Bíceps' },
  { id: 'shoulders', label: 'Hombros' },
  { id: 'abs', label: 'Abdomen' },
  { id: 'lower_back', label: 'Lumbar' },
  { id: 'forearms', label: 'Antebrazos' },
  { id: 'legs', label: 'Piernas' },
];

export const STRENGTH_EXERCISES = {
  chest: [
    'Press de banca con barra',
    'Press de banca inclinado con barra',
    'Press de banca declinado con barra',
    'Press de banca con mancuernas',
    'Press de banca inclinado con mancuernas',
    'Press de banca declinado con mancuernas',
    'Aperturas con mancuernas planas',
    'Aperturas con mancuernas inclinadas',
    'Aperturas en máquina (pec deck)',
    'Cruce de poleas alto',
    'Cruce de poleas bajo',
    'Cruce de poleas medio',
    'Press en máquina de pecho',
    'Fondos en paralelas (pecho)',
    'Pullover con mancuerna',
    'Pullover con barra',
    'Press inclinado en máquina Smith',
    'Press plano en máquina Smith',
    'Flexiones estándar',
    'Flexiones en diamante',
    'Flexiones inclinadas',
    'Flexiones declinadas',
    'Flexiones con lastre',
    'Aperturas en cables cruzados',
  ],
  back: [
    'Dominadas con agarre prono',
    'Dominadas con agarre supino',
    'Dominadas con agarre neutro',
    'Jalón al pecho en polea',
    'Jalón al pecho con agarre neutro',
    'Jalón al pecho tras nuca',
    'Remo con barra',
    'Remo con mancuerna',
    'Remo en máquina',
    'Remo en polea baja',
    'Remo en polea baja con barra',
    'Remo Pendlay',
    'T-Bar Row',
    'Remo Gironda',
    'Pull-over en polea',
    'Face Pull',
    'Peso muerto convencional',
    'Peso muerto rumano',
    'Peso muerto sumo',
    'Hiperextensiones',
    'Buenos días',
    'Remo invertido en barra',
    'Serratos con polea',
    'Remo con mancuerna a una mano',
  ],
  triceps: [
    'Press francés con barra',
    'Press francés con mancuernas',
    'Press francés en polea',
    'Extensión de tríceps en polea alta',
    'Extensión de tríceps sobre la cabeza en polea',
    'Extensión de tríceps sobre la cabeza con mancuerna',
    'Extensión de tríceps sobre la cabeza con barra',
    'Fondos en paralelas (tríceps)',
    'Fondos en banco',
    'Press cerrado con barra',
    'Pushdown en polea con cuerda',
    'Pushdown en polea con barra recta',
    'Pushdown con agarre inverso',
    'Press de tríceps en máquina',
    'Kickback con mancuerna',
    'Kickback en polea',
    'JM Press',
    'Extensión en polea alta a una mano',
    'Skull crusher con barra EZ',
    'Skull crusher con mancuernas',
  ],
  biceps: [
    'Curl de bíceps con barra',
    'Curl de bíceps con barra EZ',
    'Curl de bíceps con mancuernas',
    'Curl martillo',
    'Curl alterno con mancuernas',
    'Curl de concentración',
    'Curl en banco scott',
    'Curl en polea baja',
    'Curl en polea alta',
    'Curl inclinado',
    'Curl Zottman',
    'Curl inverso con barra',
    'Curl inverso con polea',
    'Curl con cable a una mano',
    'Curl 21s',
    'Curl araña',
    'Curl en máquina de bíceps',
    'Curl con cuerda en polea',
  ],
  shoulders: [
    'Press militar con barra',
    'Press militar con mancuernas',
    'Press Arnold',
    'Elevaciones laterales con mancuernas',
    'Elevaciones laterales en polea',
    'Elevaciones frontales con barra',
    'Elevaciones frontales con mancuernas',
    'Elevaciones frontales en polea',
    'Pájaro (elevaciones posteriores) con mancuernas',
    'Pájaro en máquina',
    'Pájaro en polea',
    'Press en máquina (hombros)',
    'Press en máquina Smith',
    'Upright row con barra',
    'Upright row con mancuernas',
    'Encogimientos de hombros (trapecio)',
    'Encogimientos con mancuernas',
    'Rotaciones externas con mancuerna',
    'Rotaciones externas en polea',
    'Face pull con cuerda',
    'Landmine press',
    'Press de hombro con kettlebell',
  ],
  abs: [
    'Crunch abdominal',
    'Crunch en máquina',
    'Crunch en polea',
    'Sit-up',
    'Plancha frontal',
    'Plancha lateral',
    'Plancha con rotación',
    'Elevación de piernas tumbado',
    'Elevación de piernas en barra',
    'Rodillas al pecho colgado',
    'Rueda abdominal (ab wheel)',
    'Russian twist',
    'Tijeras',
    'Mountain climbers',
    'Dragon flag',
    'Toes to bar',
    'Hollow body hold',
    'V-up',
    'Dead bug',
    'Cable crunch',
    'Pallof press',
    'Farmer walk',
    'Hanging knee raise',
  ],
  lower_back: [
    'Hiperextensiones en banco romano',
    'Hiperextensiones inversas',
    'Buenos días con barra',
    'Peso muerto convencional',
    'Peso muerto rumano',
    'Superman',
    'Extensiones lumbares en máquina',
    'Puente de glúteos',
    'Bird dog',
    'Palof press',
    'Suitcase carry',
  ],
  forearms: [
    'Curl de muñeca con barra',
    'Curl de muñeca inverso',
    'Extensión de muñeca con barra',
    'Curl de muñeca con mancuerna',
    'Farmer walk',
    'Dead hang',
    'Agarre en pinza',
    'Bola de agarre',
    'Pronación y supinación con mancuerna',
    'Enrollamiento de cuerda (wrist roller)',
    'Plate pinch',
    'Reverse curl',
    'Hammer curl (antebrazo)',
  ],
  legs: [
    'Sentadilla con barra',
    'Sentadilla frontal',
    'Sentadilla goblet',
    'Sentadilla búlgara',
    'Sentadilla sumo',
    'Sentadilla en máquina Smith',
    'Sentadilla hack',
    'Prensa de piernas',
    'Zancada con barra',
    'Zancada con mancuernas',
    'Zancada caminando',
    'Zancada reversa',
    'Zancada lateral',
    'Extensión de cuádriceps en máquina',
    'Curl de isquiotibiales en máquina',
    'Peso muerto rumano',
    'Peso muerto sumo',
    'Hip thrust con barra',
    'Hip thrust con mancuerna',
    'Patada de glúteo en polea',
    'Abducción de cadera en máquina',
    'Aducción de cadera en máquina',
    'Gemelos de pie en máquina',
    'Gemelos sentado en máquina',
    'Elevación de talones con barra',
    'Step-up con mancuernas',
    'Pistol squat',
    'Nordic curl',
    'Good morning',
    'Leg press inclinada',
    'Sissy squat',
    'Wall sit',
    'Glute bridge',
  ],
};

export const CARDIO_EXERCISES = [
  { id: 'run_outdoor', label: 'Correr al aire libre', unit: 'km', secondary_unit: 'min' },
  { id: 'run_treadmill', label: 'Correr en cinta', unit: 'km', secondary_unit: 'min' },
  { id: 'cycling_outdoor', label: 'Ciclismo al aire libre', unit: 'km', secondary_unit: 'min' },
  { id: 'cycling_indoor', label: 'Bicicleta estática', unit: 'km', secondary_unit: 'min' },
  { id: 'stair_machine', label: 'Máquina de escaleras', unit: 'peldaños', secondary_unit: 'min' },
  { id: 'stair_climber', label: 'Subir escaleras', unit: 'pisos', secondary_unit: 'min' },
  { id: 'treadmill_incline', label: 'Cinta inclinada (caminata)', unit: 'km', secondary_unit: 'min' },
  { id: 'rowing_machine', label: 'Máquina de remo', unit: 'metros', secondary_unit: 'min' },
  { id: 'elliptical', label: 'Elíptica', unit: 'km', secondary_unit: 'min' },
  { id: 'jump_rope', label: 'Saltar la cuerda', unit: 'saltos', secondary_unit: 'min' },
  { id: 'swimming', label: 'Natación', unit: 'metros', secondary_unit: 'min' },
  { id: 'hiit', label: 'HIIT', unit: 'min', secondary_unit: null },
  { id: 'walk_outdoor', label: 'Caminar al aire libre', unit: 'km', secondary_unit: 'min' },
  { id: 'walk_treadmill', label: 'Caminar en cinta', unit: 'km', secondary_unit: 'min' },
  { id: 'assault_bike', label: 'Assault Bike', unit: 'km', secondary_unit: 'min' },
  { id: 'ski_erg', label: 'Ski Erg', unit: 'metros', secondary_unit: 'min' },
  { id: 'versaclimber', label: 'VersaClimber', unit: 'metros', secondary_unit: 'min' },
];

export const SPORTS = [
  'Fútbol',
  'Fútbol sala',
  'Baloncesto',
  'Tenis',
  'Pádel',
  'Squash',
  'Bádminton',
  'Boxeo',
  'Kickboxing',
  'Muay Thai',
  'BJJ (Jiu-Jitsu Brasileño)',
  'Lucha libre',
  'Judo',
  'Karate',
  'Taekwondo',
  'MMA',
  'Voleibol',
  'Rugby',
  'Hockey',
  'Béisbol',
  'Senderismo',
  'Escalada',
  'Surf',
  'Skateboard',
  'CrossFit',
  'Yoga',
  'Pilates',
  'Artes marciales mixtas',
  'Waterpolo',
  'Golf',
  'Atletismo',
  'Triatlón',
];

export const getCategoryLabel = (category) => {
  const labels = { strength: 'Fuerza / Pesas', cardio: 'Cardio / Resistencia', sport: 'Deportes' };
  return labels[category] || category;
};

export const getCategoryColor = (category) => {
  const colors = {
    strength: 'text-gym bg-gym/10 border-gym/20',
    cardio: 'text-finance bg-finance/10 border-finance/20',
    sport: 'text-gold bg-gold/10 border-gold/20',
  };
  return colors[category] || '';
};

export const getCategoryDotColor = (category) => {
  const colors = { strength: '#34d399', cardio: '#60a5fa', sport: '#fbbf24' };
  return colors[category] || '#9ca3af';
};
// ============================================================
// EMOJI IMAGES for exercises, cardio and sports
// ============================================================

export const EXERCISE_IMAGES = {
  // Pecho
  'Press de banca con barra': '🏋️',
  'Press de banca inclinado con barra': '🏋️',
  'Press de banca declinado con barra': '🏋️',
  'Press de banca con mancuernas': '💪',
  'Press de banca inclinado con mancuernas': '💪',
  'Press de banca declinado con mancuernas': '💪',
  'Aperturas con mancuernas planas': '🦋',
  'Aperturas con mancuernas inclinadas': '🦋',
  'Aperturas en máquina (pec deck)': '🦾',
  'Cruce de poleas alto': '⚡',
  'Cruce de poleas bajo': '⚡',
  'Cruce de poleas medio': '⚡',
  'Press en máquina de pecho': '🦾',
  'Fondos en paralelas (pecho)': '⬇️',
  'Pullover con mancuerna': '🔄',
  'Pullover con barra': '🔄',
  'Press inclinado en máquina Smith': '🏗️',
  'Press plano en máquina Smith': '🏗️',
  'Flexiones estándar': '🤸',
  'Flexiones en diamante': '💎',
  'Flexiones inclinadas': '🔼',
  'Flexiones declinadas': '🔽',
  'Flexiones con lastre': '⚖️',
  'Aperturas en cables cruzados': '✂️',
  // Espalda
  'Dominadas con agarre prono': '🧗',
  'Dominadas con agarre supino': '🧗',
  'Dominadas con agarre neutro': '🧗',
  'Jalón al pecho en polea': '⬇️',
  'Jalón al pecho con agarre neutro': '⬇️',
  'Jalón al pecho tras nuca': '⬇️',
  'Remo con barra': '🚣',
  'Remo con mancuerna': '🚣',
  'Remo en máquina': '🦾',
  'Remo en polea baja': '⚡',
  'Remo en polea baja con barra': '⚡',
  'Remo Pendlay': '🚣',
  'T-Bar Row': '🔱',
  'Remo Gironda': '🚣',
  'Pull-over en polea': '🔄',
  'Face Pull': '🎯',
  'Peso muerto convencional': '⚓',
  'Peso muerto rumano': '⚓',
  'Peso muerto sumo': '⚓',
  'Hiperextensiones': '🌉',
  'Buenos días': '🌅',
  'Remo invertido en barra': '🔄',
  'Serratos con polea': '⚡',
  'Remo con mancuerna a una mano': '🚣',
  // Tríceps
  'Press francés con barra': '🏋️',
  'Press francés con mancuernas': '💪',
  'Press francés en polea': '⚡',
  'Extensión de tríceps en polea alta': '⚡',
  'Extensión de tríceps sobre la cabeza en polea': '⚡',
  'Extensión de tríceps sobre la cabeza con mancuerna': '💪',
  'Extensión de tríceps sobre la cabeza con barra': '🏋️',
  'Fondos en paralelas (tríceps)': '⬇️',
  'Fondos en banco': '🪑',
  'Press cerrado con barra': '🏋️',
  'Pushdown en polea con cuerda': '⬇️',
  'Pushdown en polea con barra recta': '⬇️',
  'Pushdown con agarre inverso': '⬇️',
  'Press de tríceps en máquina': '🦾',
  'Kickback con mancuerna': '🦵',
  'Kickback en polea': '⚡',
  'JM Press': '🏋️',
  'Extensión en polea alta a una mano': '⚡',
  'Skull crusher con barra EZ': '💀',
  'Skull crusher con mancuernas': '💀',
  // Bíceps
  'Curl de bíceps con barra': '💪',
  'Curl de bíceps con barra EZ': '💪',
  'Curl de bíceps con mancuernas': '💪',
  'Curl martillo': '🔨',
  'Curl alterno con mancuernas': '💪',
  'Curl de concentración': '🎯',
  'Curl en banco scott': '🪑',
  'Curl en polea baja': '⚡',
  'Curl en polea alta': '⚡',
  'Curl inclinado': '💪',
  'Curl Zottman': '🔄',
  'Curl inverso con barra': '🔄',
  'Curl inverso con polea': '🔄',
  'Curl con cable a una mano': '⚡',
  'Curl 21s': '2️⃣1️⃣',
  'Curl araña': '🕷️',
  'Curl en máquina de bíceps': '🦾',
  'Curl con cuerda en polea': '⚡',
  // Hombros
  'Press militar con barra': '🏋️',
  'Press militar con mancuernas': '💪',
  'Press Arnold': '🦸',
  'Elevaciones laterales con mancuernas': '🦅',
  'Elevaciones laterales en polea': '⚡',
  'Elevaciones frontales con barra': '🏋️',
  'Elevaciones frontales con mancuernas': '💪',
  'Elevaciones frontales en polea': '⚡',
  'Pájaro (elevaciones posteriores) con mancuernas': '🐦',
  'Pájaro en máquina': '🦾',
  'Pájaro en polea': '⚡',
  'Press en máquina (hombros)': '🦾',
  'Press en máquina Smith': '🏗️',
  'Upright row con barra': '🏋️',
  'Upright row con mancuernas': '💪',
  'Encogimientos de hombros (trapecio)': '🤷',
  'Encogimientos con mancuernas': '🤷',
  'Rotaciones externas con mancuerna': '🔄',
  'Rotaciones externas en polea': '🔄',
  'Face pull con cuerda': '🎯',
  'Landmine press': '💣',
  'Press de hombro con kettlebell': '🔔',
  // Abdomen
  'Crunch abdominal': '🤸',
  'Crunch en máquina': '🦾',
  'Crunch en polea': '⚡',
  'Sit-up': '🤸',
  'Plancha frontal': '🧱',
  'Plancha lateral': '🧱',
  'Plancha con rotación': '🔄',
  'Elevación de piernas tumbado': '🦵',
  'Elevación de piernas en barra': '🧗',
  'Rodillas al pecho colgado': '🧗',
  'Rueda abdominal (ab wheel)': '⚙️',
  'Russian twist': '🔄',
  'Tijeras': '✂️',
  'Mountain climbers': '🧗',
  'Dragon flag': '🐉',
  'Toes to bar': '🧗',
  'Hollow body hold': '🌙',
  'V-up': '✌️',
  'Dead bug': '🐛',
  'Cable crunch': '⚡',
  'Pallof press': '🎯',
  'Farmer walk': '🚶',
  'Hanging knee raise': '🧗',
  // Lumbar
  'Hiperextensiones en banco romano': '🌉',
  'Hiperextensiones inversas': '🔄',
  'Buenos días con barra': '🌅',
  'Superman': '🦸',
  'Extensiones lumbares en máquina': '🦾',
  'Puente de glúteos': '🌉',
  'Bird dog': '🐕',
  'Palof press': '🎯',
  'Suitcase carry': '💼',
  // Antebrazos
  'Curl de muñeca con barra': '💪',
  'Curl de muñeca inverso': '🔄',
  'Extensión de muñeca con barra': '💪',
  'Curl de muñeca con mancuerna': '💪',
  'Dead hang': '🙌',
  'Agarre en pinza': '🤏',
  'Bola de agarre': '🎱',
  'Pronación y supinación con mancuerna': '🔄',
  'Enrollamiento de cuerda (wrist roller)': '⚙️',
  'Plate pinch': '🖐️',
  'Reverse curl': '🔄',
  'Hammer curl (antebrazo)': '🔨',
  // Piernas
  'Sentadilla con barra': '🏋️',
  'Sentadilla frontal': '🏋️',
  'Sentadilla goblet': '🏆',
  'Sentadilla búlgara': '🦵',
  'Sentadilla sumo': '🥊',
  'Sentadilla en máquina Smith': '🏗️',
  'Sentadilla hack': '⚙️',
  'Prensa de piernas': '🦾',
  'Zancada con barra': '🏋️',
  'Zancada con mancuernas': '💪',
  'Zancada caminando': '🚶',
  'Zancada reversa': '🔄',
  'Zancada lateral': '↔️',
  'Extensión de cuádriceps en máquina': '🦾',
  'Curl de isquiotibiales en máquina': '🦾',
  'Hip thrust con barra': '🏋️',
  'Hip thrust con mancuerna': '💪',
  'Patada de glúteo en polea': '⚡',
  'Abducción de cadera en máquina': '🦾',
  'Aducción de cadera en máquina': '🦾',
  'Gemelos de pie en máquina': '🦾',
  'Gemelos sentado en máquina': '🦾',
  'Elevación de talones con barra': '🏋️',
  'Step-up con mancuernas': '👆',
  'Pistol squat': '🎯',
  'Nordic curl': '🌅',
  'Good morning': '🌅',
  'Leg press inclinada': '🦾',
  'Sissy squat': '🦵',
  'Wall sit': '🧱',
  'Glute bridge': '🌉',
};

export const CARDIO_IMAGES = {
  run_outdoor: '🏃',
  run_treadmill: '🏃‍♂️',
  cycling_outdoor: '🚴',
  cycling_indoor: '🚲',
  stair_machine: '🪜',
  stair_climber: '🧗',
  treadmill_incline: '⛰️',
  rowing_machine: '🚣',
  elliptical: '🔄',
  jump_rope: '🪢',
  swimming: '🏊',
  hiit: '⚡',
  walk_outdoor: '🚶',
  walk_treadmill: '🚶‍♂️',
  assault_bike: '🏍️',
  ski_erg: '⛷️',
  versaclimber: '🧗',
};

export const SPORT_IMAGES = {
  'Fútbol': '⚽',
  'Fútbol sala': '⚽',
  'Baloncesto': '🏀',
  'Tenis': '🎾',
  'Pádel': '🏸',
  'Squash': '🏸',
  'Bádminton': '🏸',
  'Boxeo': '🥊',
  'Kickboxing': '🥊',
  'Muay Thai': '🥊',
  'BJJ (Jiu-Jitsu Brasileño)': '🥋',
  'Lucha libre': '🤼',
  'Judo': '🥋',
  'Karate': '🥋',
  'Taekwondo': '🥋',
  'MMA': '🥊',
  'Voleibol': '🏐',
  'Rugby': '🏉',
  'Hockey': '🏑',
  'Béisbol': '⚾',
  'Senderismo': '🥾',
  'Escalada': '🧗',
  'Surf': '🏄',
  'Skateboard': '🛹',
  'CrossFit': '🏋️',
  'Yoga': '🧘',
  'Pilates': '🧘',
  'Artes marciales mixtas': '🥊',
  'Waterpolo': '🤽',
  'Golf': '⛳',
  'Atletismo': '🏃',
  'Triatlón': '🏊',
};
